### ISSUE TITLE
What is the progress of the system

### ISSUE THREAD

**Issue by youngfoo19941** [youngfoo19941/Bus-Ticketing-System#1]
guys for our bus ticketing system, I think we should have few module for it. Basically we need staff maintenance, ticketing purchase, payment... Anymore guys?

**Comment by freddywg1125** [comment]
Oh,i think that we should have feedback, because we need user opinion to improve our system, do you guys agree about it ?

**Comment by NgZuhui** [comment]
halo my dear teammates~

**Comment by YitTuckWeng** [comment]
The bus ticketing system must have the bus schedule for the driver

**Comment by youngfoo19941** [comment]
@freddywg1125 our system is offline system so i think we no need any feedback module....

**Comment by NgZuhui** [comment]
still need driver maintenance, schedule control

**Comment by teychoonwei** [comment]
and the purchase ticket and payment module

**Comment by youngfoo19941** [comment]
@YitTuckWeng ya. It will make driver easy to check their schedule and easy for our staff to arrange driver time table

**Comment by NgZuhui** [comment]
we have separate into bus schedule and driver schedule...and the driver schedule for ours bus ticketing system is suitable or not??

**Comment by youngfoo19941** [comment]
@NgZuhui i think driver only need to refer for their bus schedule because one driver one bus for permanently unless the driver resign...

**Comment by teychoonwei** [comment]
i totally agree with loh young foo, i think no need driver schedule because driver can refer back the bus schedule to confirm their schedule

**Comment by YitTuckWeng** [comment]
@youngfoo19941 that is good idea for bus schedule module

**Comment by freddywg1125** [comment]
So now we already have bus maintenance, schedule , payment module , report, staff maintenance, ticket purchasing , still have any module that i haven't mention ?

**Comment by youngfoo19941** [comment]
@freddywg1125 This is enough for an offline bus ticketing system. So any suggestion?

**Comment by YitTuckWeng** [comment]
after that, i think our system should have to generate the report like total up all the payment and some summary report.

**Comment by YitTuckWeng** [comment]
Like that we can easy to check the payment, no need check like one by one and search one by one

**Comment by youngfoo19941** [comment]
@YitTuckWeng maybe we can let user to choose the range of the date to show the report like generate report start from 12 Oct 2010 to 12 Oct 2011...

**Comment by teychoonwei** [comment]
yes, i think the report must include four report type such as purchase transaction report, payment summary report, bus exception report and the schedule summary report

**Comment by teychoonwei** [comment]
this four is the most basis report in our system

**Comment by YitTuckWeng** [comment]
@teychoonwei ya i think the four is more important for our system too

**Comment by NgZuhui** [comment]
wait~our system should have the insurance to protect our customer...give them have safety when using our service

**Comment by youngfoo19941** [comment]
OK...Staff Maintenance, Bus Maintenance, Payment, Report, Ticket Purchasing and Insurance so is it enough for our system ?

**Comment by youngfoo19941** [comment]
@freddywg1125 @NgZuhui @YitTuckWeng @teychoonwei  answer my question please

**Comment by freddywg1125** [comment]
ya, i think our system have enough modules

**Comment by NgZuhui** [comment]
that is enough for our system

**Comment by teychoonwei** [comment]
yes, i think i can handle the ticket purchasing module

**Comment by YitTuckWeng** [comment]
I have no any idea already....I think this is enough already.

**Comment by freddywg1125** [comment]
so let us decide who will handle which module, i think i will handle the staff maintenance

**Comment by youngfoo19941** [comment]
I take payment module.

**Comment by NgZuhui** [comment]
Since the insurance is suggested by me, so the insurance handle by me

**Comment by YitTuckWeng** [comment]
I suggest the bus schedule, so i take the bus schedule module

**Comment by youngfoo19941** [comment]
But how about the report module?

**Comment by teychoonwei** [comment]
i think i can handle more than one module so i take this module, everyone got any question?

**Comment by youngfoo19941** [comment]
ok i think it is done for our discussion so good luck guys...

**Comment by freddywg1125** [comment]
good luck guys 💃
